Repository Joontooling/joontooling, pull requests merged in 2023-02, with the labels that each got.

#9 feat : products app create
  config/settings.py
  config/urls.py
  products/__init__.py
  products/admin.py
  products/apps.py
  products/migrations/__init__.py
  products/models.py
  products/templates/products/index.html
  products/tests.py
  products/urls.py
  products/views.py
Labels: feat

#10 feat accounts 어플리케이션 설정
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  config/settings.py
  config/urls.py
Labels: feat

#13 feat : 모델, 폼 생성
  products/form.py
  products/migrations/0001_initial.py
  products/models.py
  products/templates/products/product_create.html
  products/urls.py
  products/views.py
  requirements.txt
Labels: feat

#16 faet : HTML 출력 확인 완료
  config/settings.py
  products/form.py
  products/templates/products/product_create.html
  products/urls.py
  products/views.py
  templates/base.html
Labels: feat

#17 feat accounts model, address
  accounts/admin.py
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  config/settings.py
Labels: feat

#18 feat : community app 및 모델 생성
  community/__init__.py
  community/admin.py
  community/apps.py
  community/migrations/__init__.py
  community/models.py
  community/tests.py
  community/views.py
  config/settings.py
  config/urls.py
Labels: feat

#19 feat community urls.py 추가
  accounts/migrations/0001_initial.py
  community/migrations/0001_initial.py
  community/models.py
  community/urls.py
  products/migrations/0001_initial.py
Labels: feat

#20 Bj 04
  products/urls.py
  products/views.py
  static/css/main.css
  static/js/main.js
  templates/base.html
Labels: feat, design

#21 design: 회원가입 레이아웃 (accounts/signup)
  accounts/forms.py
  accounts/templates/accounts/signup.html
  config/settings.py
  requirements.txt
  static/css/accounts.css
Labels: design

#22 Bj 05
  static/css/main.css
  static/js/main.js
  templates/base.html
Labels: bug, feat, design

#23 Bj 06
  static/css/main.css
  static/js/main.js
  templates/base.html
Labels: feat

#24 Bj 07
  products/templates/products/detail.html
  products/templates/products/main.html
  products/urls.py
  products/views.py
  static/css/accounts/accounts.css
  static/css/index.css
  static/css/main.css
  static/css/products/detail.css
  static/js/main.js
  templates/base.html
Labels: feat, design

#25 FEAT: 회원가입 페이지, 주소 찾기 기능 추가
  accounts/templates/accounts/signup.html
Labels: feat

#27 Bj 08
  products/templates/products/detail.html
  static/css/main.css
  static/css/products/detail.css
Labels: design

#28 Design products basket
  accounts/templates/accounts/signup.html
  products/templates/products/basket.html
  products/urls.py
  products/views.py
  static/css/main.css
  static/css/products/basket.css
  templates/base.html
Labels: design

#29 fix: 회원가입 입력필드 수정 (accounts/signup)
  accounts/templates/accounts/signup.html
Labels: bug

#30 Bj 10
  products/templates/products/detail.html
  products/templates/products/order.html
  products/templates/products/order_done.html
  products/urls.py
  products/views.py
  static/css/main.css
  static/css/products/basket.css
  static/css/products/order.css
  static/css/products/order_done.css
  static/js/main.js
  static/js/product-swiper.js
  templates/base.html
Labels: design

#32 Design accounts myshop
  accounts/templates/accounts/my_shop.html
  accounts/urls.py
  accounts/views.py
  products/templates/products/order_done.html
  static/css/accounts/my_shop.css
  static/css/main.css
Labels: design

#33 Bj 12
  accounts/templates/accounts/my_likes.html
  accounts/templates/accounts/my_posting.html
  accounts/urls.py
  accounts/views.py
  static/css/accounts/my_likes.css
  static/css/accounts/my_posting.css
  static/css/main.css
Labels: design

#37 Bj 13
  community/templates/community/index.html
  static/css/community/index.css
  static/css/main.css
  static/js/main.js
  templates/base.html
Labels: design
