Repository Joontooling/joontooling, pull requests merged in 2023-03, with the labels that each got.

#38 design: 로그인 레이아웃 (accounts/login)
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  static/css/accounts/login.css
  static/css/accounts/signup.css
Labels: design

#39 Min
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  static/css/accounts/login.css
  static/css/accounts/signup.css
Labels: design

#41 Bj 13
  community/admin.py
  community/migrations/0002_notice.py
  community/migrations/0003_alter_notice_type.py
  community/models.py
  community/templates/community/notice.html
  community/templates/community/question.html
  community/urls.py
  community/views.py
  static/css/community/index.css
  static/css/community/notice.css
  static/css/community/question.css
  static/css/main.css
  static/css/products/order.css
  static/js/question.js
Labels: feat, design

#43 FEAT: 회원가입, 로그인
  accounts/forms.py
  accounts/migrations/0002_alter_user_company.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/views.py
Labels: feat

#47 Bj 15
  images/images/info01.jpeg
  images/images/info02.png
  images/images/info03.png
  images/images/info04.png
  images/images/info05.jpeg
  images/images/info06.jpeg
  images/images/info07.jpeg
  images/images/main01.jpeg
  products/templates/products/detail.html
  products/templates/products/personal_info.html
  products/templates/products/terms.html
  products/templates/products/use_info.html
  products/urls.py
  products/views.py
  static/css/main.css
  static/css/products/detail.css
  static/css/products/footer_top.css
  templates/base.html
Labels: feat, design

#48 FEAT: 회원 수정, 비밀번호 수정, 탈퇴, 마이샵 수정
  accounts/forms.py
  accounts/models.py
  accounts/urls.py
  accounts/views.py
  templates/base.html
Labels: feat

#49 FEAT : 네브바 로그인, 회원가입, 마이쇼핑 페이지 링크 설정
  accounts/templates/accounts/my_shop.html
  accounts/urls.py
  accounts/views.py
  templates/base.html
Labels: feat

#50 Bj 16
  accounts/templates/accounts/my_likes.html
  accounts/templates/accounts/my_posting.html
  accounts/templates/accounts/my_shop.html
  community/templates/community/index.html
  community/templates/community/notice.html
  community/templates/community/qna.html
  community/templates/community/qna_list.html
  community/templates/community/question.html
  community/urls.py
  community/views.py
  products/templates/products/basket.html
  products/templates/products/detail.html
  products/templates/products/index.html
  products/templates/products/order.html
  products/templates/products/order_done.html
  static/css/community/qna.css
  static/css/community/qna_list.css
  static/css/main.css
  static/js/qna-list.js
  static/js/qna.js
Labels: design

#51 Min
  accounts/models.py
  accounts/templates/accounts/agreement1.html
  accounts/templates/accounts/agreement2.html
  accounts/templates/accounts/agreement3.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  static/css/accounts/signup.css
Labels: feat, design

#52 Feat product detail change the slider
  products/templates/products/detail.html
  static/css/products/detail.css
  static/js/product-swiper.js
Labels: feat

#54 feat: 공지사항 페이지네이션 버튼 기능 활성화
  community/templates/community/index.html
  community/templates/community/notice.html
  community/views.py
  static/css/community/notice.css
  static/css/products/detail.css
  static/js/product-swiper.js
Labels: feat

#55 Joo 0310 01
  accounts/migrations/0003_auto_20230310_1005.py
  images/5776389.jpg
  images/card_2_images_2.jpg
  images/images/5776389.jpg
  images/images/card_12_images_6.jpg
  images/images/card_15_images_3.jpg
  images/images/card_16_images_0.jpg
  images/images/card_4_images_4.jpg
  images/images/card_6_images_1.jpg
  images/images/note_20_images_1.jpg
  images/writing_39_images_2.jpg
  products/admin.py
  products/form.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20230302_1420.py
  products/migrations/0003_alter_products_image_main.py
  products/migrations/0004_alter_products_image_main.py
  products/migrations/0005_alter_products_image_main.py
  products/migrations/0006_alter_products_image_main.py
  products/migrations/0007_alter_products_image_main.py
  products/models.py
Labels: feat

#56 Joo 0310 02
  images/images/info01_kn3l5Kp.jpeg
  images/images/info02_v2aK30c.png
  images/images/info05_fizdHOd.jpeg
  images/images/info06_cX6yGVy.jpeg
  images/images/main01_LTX4Qzp.jpeg
  products/admin.py
  products/templates/products/detail.html
  products/templates/products/index.html
  products/views.py
Labels: test

#57 Bj 19
  community/models.py
  community/templates/community/notice.html
  community/views.py
  images/images/info01_iP9jrlE.jpeg
  images/images/info02_YmTIgS4.png
  images/images/info03_EgejhR5.png
  images/images/info04_83Cbo68.png
  images/images/info05_PG3wzqo.jpeg
  images/images/main01_4DYgH4u.jpeg
  images/images/main02.jpeg
  images/images/main03.jpeg
  images/images/main04.jpeg
  images/images/main05.jpeg
  products/migrations/0001_initial.py
  products/templates/products/detail.html
  products/templates/products/index.html
  static/css/community/notice.css
  static/css/main.css
  static/css/modal.css
Labels: feat, design

#58 Min
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/update.html
  static/css/accounts/update.css
Labels: bug, design

#59 update Products 모델 변경
  community/migrations/0004_alter_notice_type.py
  images/images/info01_iP9jrlE_wD2eUgd.jpeg
  images/images/info01_kn3l5Kp_VNBvuy6.jpeg
  images/images/info03_1du0wRc.png
  images/images/info04_83Cbo68_kgStz72.png
  images/images/info04_WKCQHpd.png
  images/images/info05_utJEFPz.jpeg
  images/images/info07_lHNKnZv.jpeg
  images/images/main02_gL8Ezrd.jpeg
  images/images/main04_iOQmDBr.jpeg
  products/admin.py
  products/migrations/0002_auto_20230316_1142.py
  products/migrations/0003_auto_20230316_1149.py
  products/migrations/0004_auto_20230316_1154.py
  products/migrations/0005_auto_20230316_1157.py
  products/models.py
  products/views.py
Labels: update

#60 Min
  accounts/templates/accounts/my_shop.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  accounts/views.py
  static/css/accounts/update.css
Labels: design

#61 fix: 회원유형별 필드 blank=True 적용
  accounts/forms.py
  accounts/models.py
Labels: bug

#63 Bj 20
  community/templates/community/qna.html
  community/views.py
  products/templates/products/index.html
  static/css/community/qna.css
  static/css/main.css
Labels: design

#64 Min
  accounts/templates/accounts/login.html
  accounts/templates/accounts/my_shop.html
  accounts/templates/accounts/signup.html
  static/css/accounts/login.css
  static/css/accounts/my_shop.css
  static/css/accounts/signup.css
  static/css/accounts/update.css
Labels: design

#66 design: 제품 상세 페이지 반응형 디자인 추가
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_company.py
  accounts/migrations/0003_auto_20230310_1005.py
  accounts/migrations/0004_user_like_product.py
  accounts/migrations/0005_rename_like_product_user_like_products.py
  images/images/info01_BtOhfWC.jpeg
  images/images/info02_qGrLtvF.png
  images/images/info03_lFXR9Pv.png
  images/images/info04_vlwaMmL.png
  images/images/info05_t9ygJjD.jpeg
  images/images/main01_Ep2oiRt.jpeg
  images/images/main02_081d8kN.jpeg
  images/images/main03_MQlUNeF.jpeg
  images/images/main04_6xH7IRE.jpeg
  images/images/main05_JM6f1vO.jpeg
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20230316_1142.py
  products/migrations/0003_auto_20230316_1149.py
  products/migrations/0004_auto_20230316_1154.py
  products/migrations/0005_auto_20230316_1157.py
  products/templates/products/detail.html
  static/css/main.css
  static/css/products/detail.css
  static/js/product-swiper.js
Labels: design
